version: "3"
services:
  api-gateway-nginx-internal:
    image: api-gateway-nginx-internal
    build: .
    ports:
      - "80:80"
    networks:
      - api-gateway-nginx-internal
 
networks:
  api-gateway-nginx-internal:
    driver: bridge
    